<?php


/*
 * Implementation of hook_menu()
 */
function random_numbers_table_menu(){
  // path location (<a href="http://www.url.com/foo/bar" title="http://www.url.com/foo/bar">http://www.url.com/foo/bar</a> )
  $items['random_numbers_table'] = array(
    // page title
    'title' => 'Tabela de números aleatórios',
    // describe the page for the menu system.  site visitors will not see this
    'description' => 'Gera uma tabela de números aleatórios',
    // function that is called when visiting the new path
    'page callback' => 'random_numbers_table',
    // permissions required to view page
    'access arguments' => array('access content'),
  );  
  return $items;
}

function random_numbers_table() {

  $render_array['table'] = array(
  '#theme' => 'table',
  '#header' =>  $header = array(
                  'numero'  => 'Número',
                  'remover' => 'Remover',
                ),

  '#rows' => $rows = array (

                  //row 1
                  array(
                    'numero' => rand(),
                    'remover' => '<a class="btn btn-danger btn-xs remove" href="#">X</a>',
                  ),

                  //row 2
                  array(
                    'numero' => rand(),
                    'remover' => '<a class="btn btn-danger btn-xs remove" href="#">X</a>',
                  ),

                  //row 3
                  array(
                    'numero' => rand(),
                    'remover' => '<a class="btn btn-danger btn-xs remove" href="#">X</a>',
                  ),

                  //row 4
                  array(
                    'numero' => rand(),
                    'remover' => '<a class="btn btn-danger btn-xs remove" href="#">X</a>',
                  ),

                  //row 5
                  array(
                    'numero' => rand(),
                    'remover' => '<a class="btn btn-danger btn-xs remove" href="#">X</a>',
                  ),

             ),
  );

  return $render_array;

}

?>