<?php


/*
 * Implementation of hook_menu()
 */
function meu_menu_hello_menu(){
  // path location (<a href="http://www.url.com/foo/bar" title="http://www.url.com/foo/bar">http://www.url.com/foo/bar</a> )
  $items['hello_world'] = array(
    // page title
    'title' => 'Página hello world',
    // describe the page for the menu system.  site visitors will not see this
    'description' => 'Gera uma tabela de números aleatórios',
    // function that is called when visiting the new path
    'page callback' => 'hello_world',
    // permissions required to view page
    'access arguments' => array('access content'),
  );  
  return $items;
}

function hello_world() {
  return "Hello World!";
}


?>